export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_ETH_BALANCE_SUCCESS = 'GET_ETH_BALANCE_SUCCESS';

export const UPDATE_USDT_BALANCE = 'UPDATE_USDT_BALANCE';

export const UPDATE_USDC_BALANCE = 'UPDATE_USDC_BALANCE';

export const UPDATE_BUSD_BALANCE = 'UPDATE_BUSD_BALANCE';

export const STAKE_START = 'STAKE_START';

export const STAKE_SUCCESS = 'STAKE_SUCCESS';

export const STAKE_APPROVE_START = 'STAKE_APPROVE_START';

export const STAKE_APPROVE_SUCCESS = 'STAKE_APPROVE_SUCCESS';

export const STAKE_APPROVE_FAILURE = 'STAKE_APPROVE_FAILURE';

export const STAKE_SEND_START = 'STAKE_SEND_START';

export const STAKE_SEND_SUCCESS = 'STAKE_SEND_SUCCESS';

export const STAKE_SEND_FAILURE = 'STAKE_SEND_FAILURE';

export const WITHDRAW_TOKEN_START = 'WITHDRAW_TOKEN_START';

export const WITHDRAW_TOKEN_SUCCESS = 'WITHDRAW_TOKEN_SUCCESS';

export const WITHDRAW_TOKEN_FAILURE = 'WITHDRAW_TOKEN_FAILURE';

export const SWITCH_WITHDRAW_STEP = 'SWITCH_WITHDRAW_STEP';

export const CLAIM_TOKENS_START = 'CLAIM_TOKENS_START';

export const CLAIM_TOKENS_SUCCESS = 'CLAIM_TOKENS_SUCCESS';

export const CLAIM_TOKENS_FAILURE = 'CLAIM_TOKENS_FAILURE';

export const GET_ISCLAIMABLE_SUCCESS = 'GET_ISCLAIMABLE_SUCCESS';

export const GET_CLAIMABLE_BALANCE_SUCCESS = 'GET_CLAIMABLE_BALANCE_SUCCESS';
